// This file is automatically generated by daisyUI
// Please do not edit this file directly
// If you want to customize daisyUI, please edit the daisyUI config file
//
//
// This file is used to configure Tailwind CSS
// and daisyUI.
// You can find the daisyUI config file in the root directory
// of your project.
import daisyui from 'daisyui'
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: daisyui,
  
}
